- name: Install php5
  sudo: yes
  apt: pkg=php5 state=latest

- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest="{{ php_ini }}"
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'

- name: Set error reporting
  sudo: yes
  lineinfile: dest="{{ php_ini }}"
              regexp='^error_reporting ='
              line='error_reporting = {{ php_error_reporting }}'

- name: Set display_errors
  sudo: yes
  lineinfile: dest="{{ php_ini }}"
              regexp='^display_errors ='
              line='display_errors = {{ php_display_errors }}'

- name: Set display_startup_errors
  sudo: yes
  lineinfile: dest="{{ php_ini }}"
              regexp='^display_startup_errors ='
              line='display_startup_errors = {{ php_display_startup_errors }}'

- name: Set html_errors
  sudo: yes
  lineinfile: dest="{{ php_ini }}"
              regexp='^html_errors ='
              line='html_errors = {{ php_html_errors }}'
